### ISSUE TITLE
Unable to import CSV

### ISSUE THREAD

**Issue by airbornetrooper82573** [OllisGit/OctoPrint-SpoolManager#150]
I just installed SpoolManager and attempting to upload my csv from filament manager. It never does anything. CSV Import-Status never shows a status no matter how long I let it sit for.

**Comment by Xiondewah** [comment]
I have the same issue.

**Comment by BenBetta** [comment]
Same

**Comment by rickgartner** [comment]
Same

**Comment by gleonard3** [comment]
same

**Comment by Gooz74** [comment]
same

**Comment by OllisGit** [comment]
Hi,
in the latest release V1.4.0 the issue should be fixed.

Please test and give me a feedback.

Thx, in advance
Olli

**Comment by airbornetrooper82573** [comment]
I updated to latest version, exported current Filament Manager and attempted to upload. Still showing no progress. Let it sit for a few minutes and restarted, still not showing database.

**Comment by hgross** [comment]
Had the same issue and traced it to my reverse proxy setup.
If you guys are using a proxy in front of octoprint, check #194 - also contains a workaround for nginx users.

**Comment by OllisGit** [comment]
Issue still present?
