### ISSUE TITLE
Database call error in methode loadCatalogColors

### ISSUE THREAD

**Issue by d4rken** [OllisGit/OctoPrint-SpoolManager#210]
After update to `1.5.0`

```
SPM:ERROR: DatabaseManager
Database call error in methode loadCatalogColors. See OctoPrint.log for details!
```

Log
```
2021-10-24 19:02:15,542 - octoprint.plugins.SpoolManager.DatabaseManager - INFO - Database connection succesful. Checking Scheme versions
2021-10-24 19:02:15,545 - octoprint.plugins.SpoolManager.DatabaseManager.SQL - DEBUG - ('SELECT DISTINCT "t1"."color", "t1"."colorName" FROM "spo_spoolmodel" AS "t1"', [])
2021-10-24 19:02:15,546 - octoprint.plugins.SpoolManager.DatabaseManager - ERROR - Database call error in methode loadCatalogColors
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/lib/python3.7/site-packages/octoprint_SpoolManager/DatabaseManager.py", line 703, in _handleReusableConnection
    return databaseCallMethode()
  File "/home/pi/OctoPrint/venv/lib/python3.7/site-packages/octoprint_SpoolManager/DatabaseManager.py", line 1036, in databaseCallMethode
    "colorId": spool.color + ";" + spool.colorName,
TypeError: can only concatenate str (not "NoneType") to str
2021-10-24 19:02:15,546 - octoprint.plugins.SpoolManager - WARNING - SendToClient: error#DatabaseManager#Database call error in methode loadCatalogColors. See OctoPrint.log for details!
```

**Comment by d4rken** [comment]
Viewing the db, there were 5 entries without `colorName`, afaict this is not a "mandatory" item to input in the UI, right?

I used the plugin UI to view each of the spools without `colorName` in the DB, they all showed a color name in the color name field.

I toggled the colors for each spool (select a different color then the original one again) and saved them.

The error is gone now.

I still see `Plugin not working, because of Database issues. Check Plugin-Settings!` but that was also visible before.

**Comment by OllisGit** [comment]
Hi,
in the latest version the issue should be fixed. 
Please test and give a feedback.

Thx in advance
Olli

**Comment by d4rken** [comment]
Yep, seems fixed, thanks!

This error still shows though:
https://github.com/OllisGit/OctoPrint-SpoolManager/issues/210#issuecomment-950373823

**Comment by OllisGit** [comment]
@d4rken please attach the current octoprint.log if you still see the database error.

**Comment by d4rken** [comment]
I don't think it neccessarily related to this bug, closing this in favor of #223.

Thanks for the fix! :heart:
